
# Permalinks
permalink:        pretty

# Setup
title:            Greek phonology library


baseurl: '/gsphonology/'



links:
  - title: Github source repository
    url: https://github.com/neelsmith/gsphonology
    external: true
